### ISSUE TITLE
Update to A-frame >=0.8.2 to fix critical issues with Chrome 65+ on Android

### ISSUE THREAD

**Issue by gabrielgrant** [ember-vr/ember-aframe-shim#67]
Chrome 65 introduced some breaking changes (basically movement isn't properly detected at all) that are only fixed in A-frame v0.8.2: https://github.com/aframevr/aframe/issues/3458#issuecomment-384132828

Edit: Looks like there's already [a Greenkeeper update PR](https://github.com/ember-vr/ember-aframe-shim/pull/64). Would really appreciate if you could merge that, or, if there are issues that need to be addressed, let me know and I'd be happy to see if I can tackle them

**Comment by kellyselden** [comment]
Thanks. The tests are all failing now because of the travis chrome sandbox issue. The first step would be getting that working.

**Comment by gabrielgrant** [comment]
Not 100% sure if you're talking about some specific issue with running tests in chrome on travis, or just generally that this isn't yet set up for this repo (seemed to be set up to run on firefox). Took a crack at it in #68 but waiting to see if it actually works

**Comment by gabrielgrant** [comment]
Now that CI is passing, is this just a matter of poking the [A-frame update PR](https://github.com/ember-vr/ember-aframe-shim/pull/64#issuecomment-381434333) to make sure it's OK, then merging? Or is there more of a build-step needed? (I gather this repo is doing some sort of code generation to avoid copying over A-frame components, but I'm not totally sure how it works)

**Comment by gabrielgrant** [comment]
Oh, wait, nvm -- I was confusing this with https://github.com/ember-vr/ember-aframe :man_facepalming:

**Comment by gabrielgrant** [comment]
Fixed by ember-vr/ember-aframe-shim#70
